In [2]:
import pandas as pd
import numpy as np
import seaborn as sns

In [3]:
data = pd.read_csv('cardekho.csv')

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4340 entries, 0 to 4339
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   name           4340 non-null   object
 1   year           4340 non-null   int64
 2   selling_price  4340 non-null   int64
 3   km_driven      4340 non-null   int64
 4   fuel           4340 non-null   object
 5   seller_type    4340 non-null   object
 6   transmission   4340 non-null   object
 7   owner          4340 non-null   object
dtypes: int64(3), object(5)
memory usage: 271.4+ KB

In [5]:
print(data[data.duplicated()])

                                 name  year  ...  transmission         owner
13                      Maruti 800 AC  2007  ...        Manual   First Owner
14           Maruti Wagon R LXI Minor  2007  ...        Manual   First Owner
15               Hyundai Verna 1.6 SX  2012  ...        Manual   First Owner
16             Datsun RediGO T Option  2017  ...        Manual   First Owner
17              Honda Amaze VX i-DTEC  2014  ...        Manual  Second Owner
...                               ...   ...  ...           ...           ...
4307                 Mahindra Xylo H4  2019  ...        Manual   Third Owner
4308              Maruti Alto 800 LXI  2018  ...        Manual   First Owner
4309                 Datsun GO Plus T  2017  ...        Manual   First Owner
4310  Renault Duster 110PS Diesel RxL  2015  ...        Manual   First Owner
4311          Toyota Camry Hybrid 2.5  2017  ...     Automatic   First Owner

[763 rows x 8 columns]

In [6]:
df = pd.read_csv("Projects\Regression\data\cardekho_imputated.csv")

In [7]:
df.head()

   Unnamed: 0       car_name    brand  ... max_power  seats  selling_price
0           0    Maruti Alto   Maruti  ...     46.30      5         120000
1           1  Hyundai Grand  Hyundai  ...     82.00      5         550000
2           2    Hyundai i20  Hyundai  ...     80.00      5         215000
3           3    Maruti Alto   Maruti  ...     67.10      5         226000
4           4  Ford Ecosport     Ford  ...     98.59      5         570000

[5 rows x 14 columns]

In [8]:
df.columns

Index(['Unnamed: 0', 'car_name', 'brand', 'model', 'vehicle_age', 'km_driven',
       'seller_type', 'fuel_type', 'transmission_type', 'mileage', 'engine',
       'max_power', 'seats', 'selling_price'],
      dtype='object')

In [9]:
df.drop(columns=['Unnamed: 0', 'car_name', 'brand'],axis=1,inplace=True)

In [10]:
df['model'].unique()

array(['Alto', 'Grand', 'i20', 'Ecosport', 'Wagon R', 'i10', 'Venue',
       'Swift', 'Verna', 'Duster', 'Cooper', 'Ciaz', 'C-Class', 'Innova',
       'Baleno', 'Swift Dzire', 'Vento', 'Creta', 'City', 'Bolero',
       'Fortuner', 'KWID', 'Amaze', 'Santro', 'XUV500', 'KUV100', 'Ignis',
       'RediGO', 'Scorpio', 'Marazzo', 'Aspire', 'Figo', 'Vitara',
       'Tiago', 'Polo', 'Seltos', 'Celerio', 'GO', '5', 'CR-V',
       'Endeavour', 'KUV', 'Jazz', '3', 'A4', 'Tigor', 'Ertiga', 'Safari',
       'Thar', 'Hexa', 'Rover', 'Eeco', 'A6', 'E-Class', 'Q7', 'Z4', '6',
       'XF', 'X5', 'Hector', 'Civic', 'D-Max', 'Cayenne', 'X1', 'Rapid',
       'Freestyle', 'Superb', 'Nexon', 'XUV300', 'Dzire VXI', 'S90',
       'WR-V', 'XL6', 'Triber', 'ES', 'Wrangler', 'Camry', 'Elantra',
       'Yaris', 'GL-Class', '7', 'S-Presso', 'Dzire LXI', 'Aura', 'XC',
       'Ghibli', 'Continental', 'CR', 'Kicks', 'S-Class', 'Tucson',
       'Harrier', 'X3', 'Octavia', 'Compass', 'CLS', 'redi-GO', 'Glanza',
       'Macan', 'X4', 'Dzire ZXI', 'XC90', 'F-PACE', 'A8', 'MUX',
       'GTC4Lusso', 'GLS', 'X-Trail', 'XE', 'XC60', 'Panamera', 'Alturas',
       'Altroz', 'NX', 'Carnival', 'C', 'RX', 'Ghost', 'Quattroporte',
       'Gurkha'], dtype=object)

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15411 entries, 0 to 15410
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   model              15411 non-null  object
 1   vehicle_age        15411 non-null  int64
 2   km_driven          15411 non-null  int64
 3   seller_type        15411 non-null  object
 4   fuel_type          15411 non-null  object
 5   transmission_type  15411 non-null  object
 6   mileage            15411 non-null  float64
 7   engine             15411 non-null  int64
 8   max_power          15411 non-null  float64
 9   seats              15411 non-null  int64
 10  selling_price      15411 non-null  int64
dtypes: float64(2), int64(5), object(4)
memory usage: 1.3+ MB

In [12]:
df[df.duplicated()]

             model  vehicle_age  km_driven  ... max_power seats selling_price
197           City            8      70000  ...    116.30     5        545000
360         Baleno            2       5000  ...     83.10     5        686000
1353   Swift Dzire            4      50000  ...     74.02     5        680000
1429       Wagon R           13     100000  ...     67.00     5        150000
1485           i20            3      50000  ...     81.83     5        625000
...            ...          ...        ...  ...       ...   ...           ...
15229        Swift            8      80000  ...     74.00     5        350000
15324      Wagon R            6      50000  ...     58.16     5        450000
15367        Tiago            4      30000  ...     84.00     5        350000
15378        Grand            6      30000  ...     82.00     5        450000
15392        Rover            5     128000  ...    147.50     5       2675000

[167 rows x 11 columns]

In [13]:
df.drop_duplicates(inplace=True)

In [14]:
df

          model  vehicle_age  km_driven  ... max_power seats selling_price
0          Alto            9     120000  ...     46.30     5        120000
1         Grand            5      20000  ...     82.00     5        550000
2           i20           11      60000  ...     80.00     5        215000
3          Alto            9      37000  ...     67.10     5        226000
4      Ecosport            6      30000  ...     98.59     5        570000
...         ...          ...        ...  ...       ...   ...           ...
15406       i10            9      10723  ...     68.05     5        250000
15407    Ertiga            2      18000  ...     91.10     7        925000
15408     Rapid            6      67000  ...    103.52     5        425000
15409    XUV500            5    3800000  ...    140.00     7       1225000
15410      City            2      13000  ...    117.60     5       1200000

[15244 rows x 11 columns]

In [15]:
df['fuel_type'].dtype

dtype('O')

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 15244 entries, 0 to 15410
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   model              15244 non-null  object
 1   vehicle_age        15244 non-null  int64
 2   km_driven          15244 non-null  int64
 3   seller_type        15244 non-null  object
 4   fuel_type          15244 non-null  object
 5   transmission_type  15244 non-null  object
 6   mileage            15244 non-null  float64
 7   engine             15244 non-null  int64
 8   max_power          15244 non-null  float64
 9   seats              15244 non-null  int64
 10  selling_price      15244 non-null  int64
dtypes: float64(2), int64(5), object(4)
memory usage: 1.4+ MB

In [17]:
categ = [i for i in df.columns if df[i].dtype == 'O']
num = [i for i in df.columns if df[i].dtype != 'O']

In [18]:
categ

['model', 'seller_type', 'fuel_type', 'transmission_type']

In [19]:
[df[i].unique().size for i in num]

[24, 3688, 411, 110, 342, 8, 1086]

In [20]:
dis = ['vehicle_age','seats']

### NUmerical type has two kinds discrete and continuous

In [21]:
df

          model  vehicle_age  km_driven  ... max_power seats selling_price
0          Alto            9     120000  ...     46.30     5        120000
1         Grand            5      20000  ...     82.00     5        550000
2           i20           11      60000  ...     80.00     5        215000
3          Alto            9      37000  ...     67.10     5        226000
4      Ecosport            6      30000  ...     98.59     5        570000
...         ...          ...        ...  ...       ...   ...           ...
15406       i10            9      10723  ...     68.05     5        250000
15407    Ertiga            2      18000  ...     91.10     7        925000
15408     Rapid            6      67000  ...    103.52     5        425000
15409    XUV500            5    3800000  ...    140.00     7       1225000
15410      City            2      13000  ...    117.60     5       1200000

[15244 rows x 11 columns]

In [22]:
x = df.drop(columns=['selling_price'],axis = 1)
y = df['selling_price']

In [23]:
[i for i in categ if i != 'model']

['seller_type', 'fuel_type', 'transmission_type']

In [24]:
num

['vehicle_age',
 'km_driven',
 'mileage',
 'engine',
 'max_power',
 'seats',
 'selling_price']

In [25]:
x

          model  vehicle_age  km_driven  ... engine max_power seats
0          Alto            9     120000  ...    796     46.30     5
1         Grand            5      20000  ...   1197     82.00     5
2           i20           11      60000  ...   1197     80.00     5
3          Alto            9      37000  ...    998     67.10     5
4      Ecosport            6      30000  ...   1498     98.59     5
...         ...          ...        ...  ...    ...       ...   ...
15406       i10            9      10723  ...   1086     68.05     5
15407    Ertiga            2      18000  ...   1373     91.10     7
15408     Rapid            6      67000  ...   1498    103.52     5
15409    XUV500            5    3800000  ...   2179    140.00     7
15410      City            2      13000  ...   1497    117.60     5

[15244 rows x 10 columns]

In [26]:
x

          model  vehicle_age  km_driven  ... engine max_power seats
0          Alto            9     120000  ...    796     46.30     5
1         Grand            5      20000  ...   1197     82.00     5
2           i20           11      60000  ...   1197     80.00     5
3          Alto            9      37000  ...    998     67.10     5
4      Ecosport            6      30000  ...   1498     98.59     5
...         ...          ...        ...  ...    ...       ...   ...
15406       i10            9      10723  ...   1086     68.05     5
15407    Ertiga            2      18000  ...   1373     91.10     7
15408     Rapid            6      67000  ...   1498    103.52     5
15409    XUV500            5    3800000  ...   2179    140.00     7
15410      City            2      13000  ...   1497    117.60     5

[15244 rows x 10 columns]

In [27]:
num

['vehicle_age',
 'km_driven',
 'mileage',
 'engine',
 'max_power',
 'seats',
 'selling_price']

In [28]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder,StandardScaler
from sklearn.compose import ColumnTransformer
std = StandardScaler()
lab = LabelEncoder()
ohe = OneHotEncoder(drop='first')
col = ColumnTransformer([('one hot',ohe,[i for i in categ if i != 'model']),
                        ('scalar',std,[i for i in num if i != 'selling_price'])],
                        remainder= 'passthrough')

In [29]:
[i for i in categ if i != 'model']

['seller_type', 'fuel_type', 'transmission_type']

In [30]:
[i for i in num if i != 'selling_price']

['vehicle_age', 'km_driven', 'mileage', 'engine', 'max_power', 'seats']

In [31]:
categ

['model', 'seller_type', 'fuel_type', 'transmission_type']

In [32]:
num

['vehicle_age',
 'km_driven',
 'mileage',
 'engine',
 'max_power',
 'seats',
 'selling_price']

In [33]:
x.columns

Index(['model', 'vehicle_age', 'km_driven', 'seller_type', 'fuel_type',
       'transmission_type', 'mileage', 'engine', 'max_power', 'seats'],
      dtype='object')

In [34]:
x['model'] = lab.fit_transform(x['model'])

In [35]:
x = col.fit_transform(x)

In [36]:
x = pd.DataFrame(x)

In [37]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=45,)

In [38]:
x_train

        0    1    2    3    4   ...        9         10        11        12     13
10945  1.0  0.0  0.0  0.0  0.0  ...  0.408395 -0.555669 -0.407968 -0.403299   13.0
8095   0.0  0.0  1.0  0.0  0.0  ...  1.653247 -0.457668 -0.620019 -0.403299   89.0
13790  0.0  0.0  1.0  0.0  0.0  ... -0.865240  0.977760  1.943231 -0.403299  104.0
13890  1.0  0.0  1.0  0.0  0.0  ...  0.768179 -0.457668 -0.620019 -0.403299   88.0
739    1.0  0.0  1.0  0.0  0.0  ... -1.829460  2.845545  3.280781  2.069705   74.0
...    ...  ...  ...  ...  ...  ...       ...       ...       ...       ...    ...
11808  0.0  0.0  0.0  0.0  0.0  ...  0.158945 -0.555669 -0.505838 -0.403299  117.0
6012   1.0  0.0  0.0  0.0  0.0  ... -1.037936 -0.557591 -0.643321 -0.403299   39.0
13955  1.0  0.0  1.0  0.0  0.0  ... -0.291984  0.977760  1.780115 -0.403299    1.0
6558   1.0  0.0  0.0  0.0  0.0  ... -0.371137 -0.553748 -0.433600  0.833203   62.0
7115   0.0  0.0  0.0  0.0  0.0  ...  0.276474 -0.555669 -0.407036 -0.403299   89.0

[12195 rows x 14 columns]

In [39]:
from sklearn.ensemble import RandomForestRegressor,AdaBoostRegressor,GradientBoostingRegressor
from sklearn.linear_model import LinearRegression,RidgeCV,LassoCV
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import root_mean_squared_error,r2_score,mean_absolute_error

In [40]:
def evalu(pred,truth):
    print("rmse: ",root_mean_squared_error(truth,pred))
    print("r2 score: ",r2_score(truth,pred))
    print("mae: ",mean_absolute_error(truth,pred))

In [41]:
from xgboost import XGBRegressor

In [42]:
models = {
    "RandomForest" : RandomForestRegressor(),
    "LinearRegression" : LinearRegression(),
    "Ridge regression" : RidgeCV(),
    "Lasso regression" : LassoCV(),
    "k neighbors" : KNeighborsRegressor(n_neighbors=2),
    "Decision regressor" : DecisionTreeRegressor(),
    "Addaboost" : AdaBoostRegressor(n_estimators = 60, loss = 'linear'),
    "Gradient" : GradientBoostingRegressor(n_estimators = 100, loss = 'squared_error', learning_rate = 0.3, criterion = 'squared_error'),
    "xgboost" : XGBRegressor()
}

In [43]:
for i in range (0,len(list(models))):
    model = list(models.values())[i]
    model.fit(x_train,y_train)
    y_pred = model.predict(x_test)
    print("*" * 35)
    print("\n")
    print(model)
    evalu(y_pred,y_test)

***********************************


RandomForestRegressor()
rmse:  189206.8008509689
r2 score:  0.9453657390806935
mae:  95737.84786388131
***********************************


LinearRegression()
rmse:  455464.90636965167
r2 score:  0.6834069130724238
mae:  271678.6693838645
***********************************


RidgeCV()
rmse:  455341.2004640074
r2 score:  0.6835788653584983
mae:  271401.51875096344
***********************************


LassoCV()
rmse:  456956.38947916444
r2 score:  0.681330062073322
mae:  270596.71357877477
***********************************


KNeighborsRegressor(n_neighbors=2)
rmse:  230033.6573728098
r2 score:  0.9192440824297242
mae:  105747.49918005904
***********************************


DecisionTreeRegressor()
rmse:  253987.9705081596
r2 score:  0.9015495098082287
mae:  121846.83541832607
***********************************


AdaBoostRegressor(n_estimators=60)
rmse:  471002.00949588564
r2 score:  0.6614388609276673
mae:  358675.61941188754
***********************************


GradientBoostingRegressor(criterion='squared_error', learning_rate=0.3)
rmse:  217740.55667439973
r2 score:  0.9276447172583163
mae:  107294.52382232569
***********************************


XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=None, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=None,
             n_jobs=None, num_parallel_tree=None, ...)
rmse:  206486.171875
r2 score:  0.9349310994148254
mae:  94013.1953125

In [44]:
knn_params = {"n_neighbors": [2, 3, 10, 20, 40, 50]}
add_params = {"loss" : ['linear', 'square', 'exponential'] , "n_estimators" : [50,60,70,80]}
grad_param = {'loss' : ['squared_error', 'absolute_error', 'huber', 'quantile'], "learning_rate" : [0.1,0.01,0.05,0.3],
              "n_estimators" : [50,80,100], "criterion" : ['friedman_mse', 'squared_error']}

In [45]:
randomcv = [('KNN',KNeighborsRegressor(),knn_params),
            ('addaboost',AdaBoostRegressor(),add_params),
            ('gradboost',GradientBoostingRegressor(),grad_param)]

In [46]:
from sklearn.model_selection import RandomizedSearchCV

In [47]:
model_p = {}
for name,model,param in randomcv:
    gc = RandomizedSearchCV(estimator=model,param_distributions=param,n_jobs=-1,
                                verbose=2,cv=3,n_iter=100,random_state=89)
    gc.fit(x_train,y_train)
    model_p[name] = gc.best_params_

for i in model_p:
    print(f"Best params for {i} -------")
    print(model_p[i])

Fitting 3 folds for each of 6 candidates, totalling 18 fits

c:\ProgramData\anaconda3\Lib\site-packages\sklearn\model_selection\_search.py:317: UserWarning: The total space of parameters 6 is smaller than n_iter=100. Running 6 iterations. For exhaustive searches, use GridSearchCV.
  warnings.warn(
c:\ProgramData\anaconda3\Lib\site-packages\sklearn\model_selection\_search.py:317: UserWarning: The total space of parameters 12 is smaller than n_iter=100. Running 12 iterations. For exhaustive searches, use GridSearchCV.
  warnings.warn(

Fitting 3 folds for each of 12 candidates, totalling 36 fits

c:\ProgramData\anaconda3\Lib\site-packages\sklearn\model_selection\_search.py:317: UserWarning: The total space of parameters 96 is smaller than n_iter=100. Running 96 iterations. For exhaustive searches, use GridSearchCV.
  warnings.warn(

Fitting 3 folds for each of 96 candidates, totalling 288 fits
Best params for KNN -------
{'n_neighbors': 2}
Best params for addaboost -------
{'n_estimators': 70, 'loss': 'linear'}
Best params for gradboost -------
{'n_estimators': 80, 'loss': 'squared_error', 'learning_rate': 0.3, 'criterion': 'friedman_mse'}